name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  resolve-modules:
    name: resolve modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: ./.github/tools/resolve-modules.sh
  lint:
    name: lint
    needs: resolve-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.0
          working-directory: ${{ matrix.module }}
