name: run-tests

on:
  pull_request:
  push:
    branches:
      - main
      - v2

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20' ]
        module:
          - ./log
          - ./internal
          - ./testlogger
          - ./middleware
          - ./logrus
          - ./zerolog
          - ./logrus
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: run-tests
        run: go test ./... -v -race -failfast -count 100
        working-directory: ${{ matrix.module }}
