name: run-tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  resolve-modules:
    name: resolve modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: ./.github/tools/resolve-modules.sh
  test:
    name: test
    needs: resolve-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20', '1.21', '1.22', '1.23' ]
        module: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go }}'
      - name: run-tests
        run: go test ./... -v -race -failfast -count 100
        working-directory: ${{ matrix.module }}
